### ISSUE TITLE
Observations about retrieving info

### ISSUE THREAD

**Issue by anthonyryan1** [Dalimil/Eventbrite-Tools#4]
I tried using this today but observed the info script printing faulty information. While I don't have a patch, I discovered that this seems to be the best way to get event / ticket information now.

```javascript
require(['mediatorjs'], function(mediator) {
    var options = mediator.get('ticketOrderOptions');

   // options contains detailed information about tickets including availability time, sale status, etc.
});
```

**Comment by Dalimil** [comment]
Thanks. We're still missing a few fields though - I'm not sure if the quantity_sold is hidden somewhere or if they stopped sending this information altogether. Hint: This is new: `"json_blacklist_set": ["event_tz", "event_level_info", "quantity_sold", "quantity_remaining", "request", "quantity_total", "waitlist_settings", "taxoptions"]`

**Comment by cwhitney1234** [comment]
To pull the ticket quantity check the "inventoryLevel" field.  It lists the correct value.

**Comment by Dalimil** [comment]
Thanks, added: f01d469

**Comment by danksy13** [comment]
Hello there i tried running the script today just to get event info but i could not get it to work. is the script outdated? this is the event i was trying to get the info for if anyone could help me out it would definitely be appreciated!

https://www.eventbrite.com/e/funko-fundays-2017-tickets-34213467402

**Comment by Dalimil** [comment]
@danksy13 `ticket-info.js` works just fine for the event you mentioned, just follow the setup instructions and it should work...

**Comment by danksy13** [comment]
i got it working! thanks! Is there anyway to find out how many tickets sold? all im getting is the "Quantity_Remaining" under quantity.

**Comment by elmiguerto** [comment]
Hi! thank for your work! I would like to use info.js it´s already working?
