### ISSUE TITLE
sales_start time & timezone

### ISSUE THREAD

**Issue by FabianWu** [Dalimil/Eventbrite-Tools#5]
I'm setting up for an event tomorrow where the the time of the event is Noon PDT, yet the code shows a different sales_start date/time with no timezone

My question is: What time should I set ticketgetter for? 

Thanks

<img width="1146" alt="screen shot 2018-04-14 at 11 49 47 am" src="https://user-images.githubusercontent.com/38381548/38770540-12e077be-3fda-11e8-983d-8b70efafb75b.png">

**Comment by Dalimil** [comment]
The script is converting to your local time, so that's the time you will need.
